Repository f-lab-edu/red-yoo-toss-tech, pull requests merged in 2023-02, with the labels that each got.

#8 Issue 6 PR Issue 템플릿 작성
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📄Docs, ⚙️Setting

#7 Issue 5 코드컨벤션 환경세팅
  .eslintrc.js
  .prettierrc
  package.json
  yarn.lock
Labels: ⚙️Setting

#14 Issue 13 Footer-Section HTML,CSS 구현
  index.html
  public/component/FooterComponent.js
  public/component/NavComponent.js
  public/img/icon-blog.svg
  public/img/icon-facebook.svg
  public/img/icon-instagram.svg
  public/img/icon-naver.svg
  public/img/icon-twitter.svg
  public/img/toss-icon.png
  style.css
Labels: 🎨 Html&CSS

#20 Issue 19 README img 안보이는 형상 해결
  README.md
Labels: 🐞 BugFix

#22 Issue 18 게시글 더미 데이터 작성
  MOCK_DATA.json
Labels: 📄Docs

#21 Issue 17 main content 마크업 css
  src/component/MainComponent.js
  src/img/content1.png
  src/main.js
  style.css
Labels: 🎨 Html&CSS

#24 Refactor: Component파일 코드 class형식으로 리팩토링
  index.html
  src/component/FooterComponent.js
  src/component/MainComponent.js
  src/component/NavComponent.js
  src/main.js
Labels: 🔨 Refactor
