Repository f-lab-edu/red-yoo-toss-tech, pull requests merged in 2023-04, with the labels that each got.

#41 Feat: mainComponent 태그를 div를 바꾼 후 클릭이벤트 위임
  src/component/MainComponent.js
  src/router.js
  style.css
Labels: ✨ Feature

#43 Issue 42 main component type script로 마이그래이션
  src/component/MainComponent.js
  src/component/Maincomponent.js.map
  src/component/Maincomponent.ts
  tsconfig.json
Labels: 🔨 Refactor

#49 Issue 48 json data가 article로 넘어가지 않는 에러 수정
  .gitignore
  src/component/DesignComponent.js
  src/component/DesignComponent.js.map
  src/component/DesignComponent.ts
  src/component/MainComponent.js
  src/component/Maincomponent.js.map
  src/component/Maincomponent.ts
  style.css
Labels: 🐞 BugFix

#52 Issue 36 폰트 설정
  style.css
Labels: 🎨 Html&CSS

#54 Issue 53 게시글 클릭 시 스크롤 초기화 수정
  src/router.js
Labels: 🐞 BugFix

#55 Issue 50 Article Component 새로고침시 데이터 오류 수정
  src/router.js
Labels: 🐞 BugFix

#57 Issue 56 .js, .map파일 원격저장소에서 파일 삭제
  src/component/ArticleComponent.js
  src/component/ArticleComponent.js.map
  src/component/DesignComponent.js
  src/component/DesignComponent.js.map
  src/component/FooterComponent.js
  src/component/FooterComponent.js.map
  src/component/MainComponent.js
  src/component/Maincomponent.js.map
  src/component/NavComponent.js
  src/component/NavComponent.js.map
Labels: 🐞 BugFix
